### PR TITLE
[WIP] Time series forecast v0.2.0 update

### PR DESCRIPTION
**Pull request by alexcombessie**
- add support for multivariate forecasting
- misc. bugfixes

### CODE REVIEW

**Comment by alexcombessie** [comment]
@jereze PR ready for review!

 In this new minor version, I have added support of external regressors for Neural Network, Prophet and ARIMA models. Note that this requires availability of future values of regressors when forecasting. The implementation has been tested on multiple datasets with several configurations.

I have also revamped the README to reflect these changes and harmonize the format. Could you use it to update the plugin page on our website? I have noted some minor inconsistencies, mostly outdated screenshots of the recipes.

**Comment by alexcombessie** [comment]
@jereze I have made the requested change to the README. I will also make a PR to update the website doc.

**Comment by alexcombessie** [comment]
Thanks @jereze! @du-phan can you give it a try? I have tested on my side, but it never hurts to be sure 🌞

**Comment by alexcombessie** [comment]
ping @du-phan if you have some time to test the new version?

**Comment by du-phan** [comment]
Hey sure I will test it later this week!

**Comment by alexcombessie** [comment]
thanks! let me know when you deem it ready to merge!

**Comment by du-phan** [comment]
I test it on local and everything looks good to me! @jereze we can push it to the store if you wish!

**Pull request merged**
