### PR TITLE
Project migration v2

### PR DESCRIPTION
**Pull request by du-phan**

### CODE REVIEW

**Comment by pmasiphelps** [comment]
@du-phan I get an error when running the push to Design instance macro, when the "Create code env" checkbox is checked. Here's a screenshot. The error says "dataikuapi.utils.DataikuException: java.lang.ClassCastException: com.dataiku.dip.code.CodeEnvModel$DesignUIREnv cannot be cast to com.dataiku.dip.code.CodeEnvModel$DesignUIPythonEnv", so something to do with the dataiku API. it thinks that we're setting a remote R env with a python env's params? did you get this error when you tested it? 
Screen Shot 2019-11-12 at 9 49 28 PM

**Comment by du-phan** [comment]
Good catch, I'll have a look!

**Comment by du-phan** [comment]
Apparently it is a bug with DSS, upgrading to 6.0.1 fixed it.
https://app.clubhouse.io/dataiku/story/43085/bundle-migration-r-env-creation-throws-back-error

**Comment by rikroe** [comment]
It would be great if the checkbox `Activate Scenarios` would also make sure that the project settings option `Automation` > `Disable automatic triggers` is unchecked.

In `activate_remote_scenario`, add the following:
```
prj_settings = self.project.get_settings()
prj_settings .settings['settings']['disableAutomaticTriggers'] = False
prj_settings .save()
```

**Pull request closed without merging**
